# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: f1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'f1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66\x31.proto\"\xab\x01\n\x0c\x43\x61rTelemetry\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04team\x18\x03 \x01(\t\x12\x12\n\nfront_left\x18\x04 \x01(\x01\x12\x13\n\x0b\x66ront_right\x18\x05 \x01(\x01\x12\x11\n\trear_left\x18\x06 \x01(\x01\x12\x12\n\nrear_right\x18\x07 \x01(\x01\x12\x10\n\x08position\x18\x08 \x01(\x05\x12\x11\n\ttimestamp\x18\t \x01(\x01\"\x1d\n\nStoreReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32=\n\x0bSACPService\x12.\n\x0eStoreTelemetry\x12\r.CarTelemetry\x1a\x0b.StoreReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'f1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARTELEMETRY']._serialized_start=13
  _globals['_CARTELEMETRY']._serialized_end=184
  _globals['_STOREREPLY']._serialized_start=186
  _globals['_STOREREPLY']._serialized_end=215
  _globals['_SACPSERVICE']._serialized_start=217
  _globals['_SACPSERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
